name: Build, test, and deploy app

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setting up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Installing dependencies
        run: npm ci

      - name: Running test
        run: npm run test

      - name: Building JS from TS files
        run: npm run ts:build

      - name: Building CSS from Tailwind
        run: npm run css:build

      - name: Checking if dist folder has been created
        run: ls dist

      - name: Copying images to dist folder
        run: cp -R images dist/images

      - name: Copying index.html to dist folder
        run: cp index-copy.html dist

      - name: Setting up GH Pages
        uses: actions/configure-pages@v3

      - name: Uploading artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./dist/"

      - name: Deploying to GH Pages
        id: deployment
        uses: actions/deploy-pages@v1
